bubbleTexts = {

"What is this?",    
"Kill...",
"Transform!",
"Im bored",
"waiting",
"I hate thunder",
"I love thunder",
"I hate water",
"I love water",
"its magical",
"I love fields",
"I love mountains",
"I love you",
"I forgot...",
"nananana",
"mumblemumble",
"FIRE",
"I love lakes",
"Im wet",
"Sleep now in the FIRE",
"...",
"My tummy growls",
"lets go",
"cant wait",
"bangbangbang",
"im full of energy",
"im tired",
"dont let them flee",
"why cant we fly",
"lets leave this tile",
"pass this turn",
"progress forward!",
"im gonna retire now",
"lets approach the enemies",
"cruise this land",
"ambush them!",
"lets assault from the front",
"beat them now",
"CHAARGE",
"thats gonna hurt",
"i stink",
"kem-pe-len",
"hm",
"i hate AirElementals",
"i love food. You?",
"gimme chocolate",
"you can do things back",
"go home",
"we are wicked sick",
"i love the breeze of the sea",
"lets start over",
"im dead inside",
"everythings fine",
"bad move",
"nice",
"capitalism is bad",
"i hope they do better next time",
"i'm here!!!",
"leave me alone",
"<3 you",
"WHY?",
"HOW?",
"please shut up",
"why would we talk?",
"i hope we win",
"i fear of losing",
"did you ever heard about Kaosz Elemer?",
"YOU are the best in this game"








}

return bubbleTexts